# Generated by Django 4.0.6 on 2022-11-02 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_ingredientinrecipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Value cannot be less than 1')], verbose_name='Cooking time in minutes'),
        ),
    ]
