# Generated by Django 4.0.6 on 2022-11-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'default_related_name': 'recipe_ingredients', 'verbose_name': 'Amount ingredients in recipe', 'verbose_name_plural': 'Amount ingredients in recipes'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'default_related_name': 'tags', 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
