# Generated by Django 4.0.6 on 2022-11-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_ingredientinrecipe_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Add image', null=True, upload_to='recipe/images', verbose_name='Image'),
        ),
    ]
