# Generated by Django 4.0.6 on 2022-11-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_alter_ingredientinrecipe_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'default_related_name': 'recipe_ingredients', 'ordering': ['id'], 'verbose_name': 'Amount ingredients in recipe', 'verbose_name_plural': 'Amount ingredients in recipes'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-id'], 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
    ]
