# Generated by Django 4.0.6 on 2022-11-19 19:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0013_alter_ingredientinrecipe_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopping_list',
            new_name='ShoppingList',
        ),
    ]
