# Generated by Django 4.0.6 on 2022-11-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_rename_shopping_list_shoppinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Name'),
        ),
    ]
