version: '3.3'
services:
  db:
      image: postgres:12.4
      volumes:
        - /var/lib/postgresql/data/
      env_file:
        - ../backend/foodgram/foodgram/.env

  backend:
    image: lanazzk/foodgram:latest
    restart: always
    volumes:
      - app/static/
      - app/media/
    depends_on:
      - db
    env_file:
      - ../backend/foodgram/foodgram/.env

  frontend:
    image: lanazzk/foodgram:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - /app/static/
      - /app/media/
      - /var/html/static/
      - /var/html/media/
    restart: always
    depends_on:
      - backend
      - frontend
volumes:
  static_value:
  media_value:
  db_value:

